---
- hosts: all
  remote_user: root
  become: yes
  become_method: sudo
  gather_facts: no
  connection: ssh
  tasks:
   - name: add user "drew"
     user:
       name: drew
       comment: Drew DeVore
       password: $6$OOm/Gq51HW8I$tk8QjMicx7j1L.Y7mWaHkf/gS/7Y6fbwooIfPzbVs9O37T20NaPv0aLUiAv22lQ07y2OGqujn7pbG6W9v/sEN0
       uid: 1010
       group: users
       groups: wheel
       append: yes
       state: present
       shell: /bin/bash

   - name: add SSH key
     authorized_key:
       user: drew
       state: present
       key: ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBERBG2OnlC2jKFF0/nrWwjohdDRRRAuhgUjopwUKj5RA9t2DnWQ+VAMC5pl7ZBwx9eom6QAFSjwjrvPm61u2/X8= drew@devorcula.com
...