---
# The name of ssh daemon
sshd: sshd
# Where is ssh config is located at
sshd_config: /etc/ssh/sshd_config

- hosts: all
  roles:
    - { role: ., sshd: sshd, sshd_config: /etc/sshd_config }
  tasks:
    - name: Disable empty password login
      lineinfile: dest={{ sshd_config }} regexp="^#?PermitEmptyPasswords" line="PermitEmptyPasswords no"
      notify: restart sshd
    
    - name: Disable remote root login
      lineinfile: dest={{ sshd_config }} regexp="^#?PermitRootLogin" line="PermitRootLogin no"
      notify: restart sshd
    
    - name: Disable password login
      lineinfile: dest={{ sshd_config }} regexp="^(#\s*)?PasswordAuthentication " line="PasswordAuthentication no"
      when: add_identity_key is succeeded and not add_identity_key is skipped
      notify: restart sshd
    
    - name: Enable PAM
      lineinfile: dest={{ sshd_config }} regexp="^#?UsePAM" line="UsePAM yes"
      notify: restart sshd