---
- hosts: all
  remote_user: root
  become: yes
  become_method: sudo
  gather_facts: no
  connection: ssh
  tasks:
  - name: update system
    dnf:
      name: "*"
      state: latest

  - name: restart system to reboot to newest kernel
    shell: "sleep 5 && reboot"
    async: 1
    poll: 0
 
  - name: wait for 10 seconds
    pause:
      seconds: 10
 
  - name: wait for the system to reboot
    wait_for_connection:
      connect_timeout: 20
      sleep: 5
      delay: 5
      timeout: 60
 
  - name: install epel-release
    dnf:
      name: epel-release
      state: latest
...